# 项目相关配置
linq:
  # 名称
  name: Linq
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 文件路径 示例（ Windows配置D:/linq/uploadPath，Linux配置 /home/linq/uploadPath）
  profile: /Users/jay/Desktop/Vue项目集合/新闻发布管理系统/linq/uploadPath
  #  profile: /home/linq/uploadPath
  # 获取ip地址开关
  addressEnabled: true


# 登录相关配置
login:
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

#jwt
jwt:
  header: Authorization   # 令牌前缀
  token-start-with: Bearer   # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-minutes: 30   # 令牌过期时间 默认30min


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /prod-api


# 日志配置
logging:
  level:
    com.linq: debug
    org.springframework: debug

## 爬虫地址
#spider:
#  csdnNews:
#    # 请求地址
#    url: https://blog.csdn.net/nav/java
#    # 详情页目标链接地址css选择器
#    targetUrlCssSelector: '.clearfix'
#    # 获取所有详情页列表css选择器
#    detailSelectCssSelector: '.baidu_pl'
#    # 标题css选择器
#    newsTitleCssSelector: '#articleContentId'
#    # 类型id
#    newsTypeId: 18
#    # 文章内容css选择器
#    newsContentCssSelector: '#article_content'
#    # 文章封面css选择器
#    newsImageCssSelector: '.avatar_pic'
#    # key值
#    fieldKey: 'csdnNews'
#  peNews:
#    # 请求地址
#    url: http://sports.sina.com.cn/nba/
#    # 详情页目标链接地址css选择器
#    targetUrlCssSelector: 'div.news-list-b'
#    # 获取所有详情页列表css选择器
#    detailSelectCssSelector: '.main-content.w1240'
#    # 标题css选择器
#    newsTitleCssSelector: '.main-title'
#    # 类型id
#    newsTypeId: 4
#    # 文章内容css选择器
#    newsContentCssSelector: '#artibody'
#    # 文章封面css选择器
#    newsImageCssSelector: '.img_wrapper > img'
#    # key值
#    fieldKey: 'peNews'


#    peNewsUrl: http://sports.sina.com.cn/nba/ # 体育新闻
#    entertainmentNewsUrl: https://ent.sina.com.cn/star/ # 娱乐新闻
#    csdnUrl: https://blog.csdn.net/nav/java # csdn博客
