# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9000
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  messages: # 资源信息
    basename: i18n/messages  # 国际化资源文件路径
  profiles:
    active: druid,linq # 子配置文件
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #    default-property-inclusion: non_null   # 处理 jackson 返回的null值 不显示出来 只显示不为null的
  # 解决多模块全局异常拦截失效
  #  mvc:
  #    throw-exception-if-no-handler-found: true # 出现错误时,直接抛出异常
  #  resources:
  #    add-mappings: false # 关闭工程中的资源文件建立映射
  redis:
    expire: 60000 # 过期时间
    database: 0 # Redis使用的库
    host: 39.108.104.116
    port: 56379 #端口号
    password: lyq@qq.com  #redis密码
    timeout: 10000        #  连接超时时间（毫秒）
    cache:
      type: redis           #使用redis做缓存
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 消息中间件 rabbitMQ
  rabbitmq:
    virtual-host: / # 配置虚拟机
    host: server.kaiyu.work # ip
    port: 5672 # 端口
    username: admin # 用户名
    password: 111222 # 密码
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  devtools: # 服务模块
    restart:
      enabled: true       # 热部署开关
# elasticsearch 配置 这里是坑 还得装head插件 之前的cluster.name nodes那些都不适用了 会抛出 拒绝连接错误
  elasticsearch:
    rest:
      uris: ["http://120.79.43.16:9200"]
# mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 开启驼峰命名法
  global-config:
    db-config:
      logic-delete-value: 2 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


